mysql: 
  port: 3306
  address: "localhost"
  username: "root"
  password: "123456"
  db: "regulus_main"

log:
  path: "/Users/jackielee/Documents/devworkspace/my_workspace/regulustar/log/info.log"
  node: "/Users/jackielee/Documents/devworkspace/my_workspace/regulustar/log/info-node.log"
  level: "debug"
