mysql: 
  port: 3306
  address: "localhost"
  username: "root"
  password: "123456"
  db: "routerp"

log:
  path: "/Users/jackielee/Documents/devworkspace/vega_workspace/vegax_backend/log/info.log"
  node: "/Users/jackielee/Documents/devworkspace/vega_workspace/vegax_backend/log/info-node.log"
  level: "debug"
