mysql: 
  port: 3306
  address: "mpc-wallet-prod.cg38dsr0jgnb.ap-southeast-1.rds.amazonaws.com"
  username: "dev"
  password: "WpcMalletDev3345221"
  db: "regulus_main"

log:
  path: "/Users/jackielee/Documents/devworkspace/my_workspace/regulustar/log/info.log"
  node: "/Users/jackielee/Documents/devworkspace/my_workspace/regulustar/log/info-node.log"
  level: "debug"
