mysql: 
  port: 3306
  address: "localhost"
  username: "root"
  password: "routerpassword"
  db: "router_main"

log:
  path: "/home/env/go/log/info.log"
  node: "/home/env/go/log/info-node.log"
  level: "warn"